### PR TITLE
GREEN-6530/Post prospect docs

### PR DESCRIPTION
**Pull request by akrulwich**
https://greenhouseio.atlassian.net/browse/GREEN-6530

### CODE REVIEW

**Comment by mmurph24** [comment]
This one should be POST instead of PATCH also. The job_id section doesn't work with prospects, so we should either create a bug card to make that work or remove it from the documentation.

**Comment by akrulwich** [comment]
@mmurph24 You sure it doesn't work? https://www.dropbox.com/s/w7dzcedi99zk3kd/Screenshot%202016-12-22%2010.13.29.png?dl=0

**Comment by akrulwich** [comment]
```
2.2.4 :240 > Application.find(29843270).hiring_plan
  Application Load (0.3ms)  SELECT  "applications".* FROM "applications" WHERE "applications"."id" = $1 LIMIT 1  [["id", 29843270]]
[#8206] DEBUG -- : [] Application Load (0.3ms)  SELECT  "applications".* FROM "applications" WHERE "applications"."id" = $1 LIMIT 1  [["id", 29843270]]
  HiringPlan Load (25.4ms)  SELECT  "hiring_plans".* FROM "hiring_plans" WHERE "hiring_plans"."id" = $1 LIMIT 1  [["id", 218420]]
[#8206] DEBUG -- : [] HiringPlan Load (25.4ms)  SELECT  "hiring_plans".* FROM "hiring_plans" WHERE "hiring_plans"."id" = $1 LIMIT 1  [["id", 218420]]
 => #<HiringPlan id: 218420, created_at: "2016-04-11 19:54:09", updated_at: "2016-05-26 17:41:24", job_type_id: 65, seniority_id: 1, name: "Order Processing Associate, Returns (FT Temp)", organization_id: 722, close_date: "2016-05-26 17:41:24", open_date: "2016-04-11 19:54:09", hiring_plan_status_id: 2, notes: "Looking for the best!", anywhere: false, requisition_id: nil, salary: nil, bonus: nil, options: nil, created_by_id: 11527, team_and_responsibilities: "<p>https://docs.google.com/document/d/1sv_pr7-jW8q...", how_to_sell_this_job: nil, import_hash: nil, original_job_id: nil, original_migration_id: nil, confidential: false>
```

**Comment by akrulwich** [comment]
^ I guess that's the wrong job? But it doesn't error

**Comment by mmurph24** [comment]
The prospect is created without any error, but they are not put on the job that was specified.

screen shot 2016-12-22 at 9 57 39 am

screen shot 2016-12-22 at 9 56 34 am

**Comment by akrulwich** [comment]
Ok, so for the time being the solution would be to remove the
"applications" key entirely?

**Comment by mmurph24** [comment]
Yea, I think that makes sense.

**Pull request merged**
