### PR TITLE
Add info about PATCHing prospect pool data

### PR DESCRIPTION
**Pull request by robnormal**
For this:
https://github.com/grnhse/greenhouse/pull/9250

### CODE REVIEW

**Comment by mmurph24** [comment]
@richeyb Can we ship this one again now that Rob's card is actually out?

**Comment by mmurph24** [comment]
Actually @robnormal can you rebase and update the change log date so @richeyb can ship this when you get a chance?

**Comment by robnormal** [comment]
Looks like the changes were already pushed to master?

**Comment by mmurph24** [comment]
Yea but then it was rolled back....Does that mean we need a new PR altogether?

**Comment by robnormal** [comment]
Yeah, I created https://github.com/grnhse/greenhouse-api-docs/pull/304
But it looks like the actual document change - as opposed to the change log change - is still in the master branch

**Comment by robnormal** [comment]
OK, I rebased wrong. Here ya go https://github.com/grnhse/greenhouse-api-docs/pull/305

**Pull request merged**
